spring:
  application:
    name: categories-service
  config:
    import: "optional:configserver:http://localhost:8081"
  cloud:
    config:
      uri: http://localhost:8081
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
