server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jdoradoc/microservices-examples.git
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          search-paths: config-data
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}